_base_: default

data:
  dataset_root: /home/linux/artcap-blip2-4/artquest/data
  dataset_name: artquest
  train_split: artquest_train
  val_split: artquest_val
  test_split: artquest_test
  caption_key: question
  style_key: style
  image_root: /home/linux/artcap-blip2-4/artquest/data/SemArt/Images
  batch_size: 32
  num_workers: 8
  image_size: 224

model:
  gating:
    type: film
    per_head: true
    hidden_dim: 768

training:
  max_epochs: 15
  gradient_accumulation: 2
  lr: 5.0e-5
  warmup_steps: 2000

loss:
  style_hit_weight: 0.1
  consistency_kl_weight: 0.05
